name: Fly Deploy
on:
  push:
    branches: 'master'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: fly deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: sudo apt-get -y --no-install-recommends install libdancer-perl
        - run: for f in app.psgi bin/app.pl lib/*.pm lib/**/*.pm public/*.dat; do perl -cw $f; done
        - run: flyctl deploy --remote-only
