name: Fly Deploy
on:
  push:
    branches: 'master'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: fly deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: apt-get -qq -y --no-install-recommends install libdancer-perl
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: perl -cw bin/app.pl
        - run: flyctl deploy --remote-only
